### PR TITLE
Carthage support

### LINKED ISSUE #3: Carthage support

### PR DESCRIPTION
**Pull request by JanC**
Added targets and shared schemes so that Carthage compiles on other platforms that iOS

- [x] added macOS target
- [x] added watchOS target
- [x] added tvOS target

fixes #3

### CODE REVIEW

**Comment by ethanhuang13** [comment]
Thanks, I'll take a look later.

**Comment by JanC** [comment]
It's still WIP .. I'm testing if it compiles and runs correctly on all the platforms

**Comment by JanC** [comment]
all platforms now compile
```
carthage build
*** Building scheme "CupertinoJWT iOS" in CupertinoJWT.xcodeproj
*** Building scheme "CupertinoJWT macOS" in CupertinoJWT.xcodeproj
*** Building scheme "CupertinoJWT watchOS" in CupertinoJWT.xcodeproj
*** Building scheme "CupertinoJWT tvOS" in CupertinoJWT.xcodeproj
```

**Comment by ethanhuang13** [comment]
Thanks. I've verify on an example app and it works well.

**Pull request merged**
