### PR TITLE
Changed Header and payload to current API

### PR DESCRIPTION
**Pull request by doozMen**
I guess it was different before. Added some keys and now it works for me at least.

### CODE REVIEW

**Comment by ethanhuang13** [comment]
Please separate each commit to different PRs. 

Also, the keys are for APNs and DeviceCheck. Please add another file for App Store Connect API instead.

**Comment by ethanhuang13** [comment]
Close the PR because you should separate each commit to different PRs.

**Comment by doozMen** [comment]
@ethanhuang13 closing a pr because each commit needs to be a PR is not really a reason. Also what I did actually works and is needed. So I will look into it but I tried to help you. Why the defence?

**Comment by doozMen** [comment]
> Please separate each commit to different PRs.
> 
> Also, the keys are for APNs and DeviceCheck. Please add another file for App Store Connect API instead.

Thanks for this comment but. I will change this in issue #10

**Comment by ethanhuang13** [comment]
> @ethanhuang13 closing a pr because each commit needs to be a PR is not really a reason. Also what I did actually works and is needed. So I will look into it but I tried to help you. Why the defence?

"fix signing"(4bd366905ab595af4fbdd0e0b8380ca79e98d316) is not a fix, you've just change to what you need(manual) and its **not related to App Store Connect API.** These three commits 3c49575f1bcf2f89e77aaa5dd82960ed197dbfdb, 99728e12276b6f97c3921d9703ca0d11ad1b923d, and 9f097526722e5ade405a7480973623e1aedac4a9 have the same situation.

If you separate them as different PRs, I can accept them.

**Comment by doozMen** [comment]
@ethanhuang13 I have read your ReadMe and also the link to the article related to the commits. Interesting point of view. I will read it and make it better. Just I thought this was already a small PR. Also I made a mistake in thinking your frameworks was only for App Store Connect. It is not so I will change that. So I was a bit quick in asking why you rejected, sorry.

**Pull request closed without merging**
